### <h1><center style="font-size: 48px">Coordinate transformations</center></h1>
<br><br>

Some reference points for checks:

$\bf 1- ~Galactic ~North ~pole ~(+90° ~latitude)$ 	12h 51.4m 	+27.13° 	Coma Berenices
(near 31 Com)

Input: Galactic 
RA or Longitude   DEC or Latitude   PA(East of North)
0.00000000      90.00000000       0.000000     

$\bf Output: ~Equatorial ~J2000.0$

192.85948402      27.12829637       302.931981   
12h51m26.27616s   +27d07m41.8669s


$\bf 2- ~Galactic ~South ~pole ~(−90° ~latitude)$ 	0h 51.4m 	−27.13° 	Sculptor
(near NGC 288)

Input: Galactic 
RA or Longitude   DEC or Latitude   PA(East of North)
0.00000000        -90.00000000      0.000000     

$\bf Output: ~Equatorial ~J2000.0$

12.85946451       -27.12820428      237.068156   
00h51m26.27148s   -27d07m41.5354s

$\bf 3- ~Galactic~ center~ (0° ~longitude)$ 	17h 45.6m 	−28.94° 	Sagittarius
(Galactic Center)

Input: Galactic 
RA or Longitude   DEC or Latitude   PA(East of North)
0.00000000        0.00000000        0.000000     

$\bf Output: ~Equatorial~ J2000.0$

266.40508920      -28.93617470      301.401202   
17h45m37.22141s   -28d56m10.2289s

$\bf 4- ~Anti-center ~(180° ~longitude)$ 	5h 45.6m 	+28.94° 	Auriga
(near HIP 27088)

Input: Galactic 
RA or Longitude   DEC or Latitude   PA(East of North)
180.00000000      0.00000000        0.000000     

$\bf Output:~ Equatorial ~J2000.0$

86.40489195       28.93616388       58.598539    
05h45m37.17407s   +28d56m10.1900s

Coordinate transformation page:
http://www.atnf.csiro.au/people/Tobias.Westmeier/tools_coords.php

online calculation tool: https://ned.ipac.caltech.edu/forms/calculator.html

In [2]:
import healpy as hp
import numpy as np

healpy Rotator take co-Lat (=$\pi/2$-Lat) and Lon as input, in radian by default. It returns co-Dec and RA in degrees by default.

### <h1><center style="font-size: 24px">Using Healpy</center></h1>

In [12]:
r = hp.rotator.Rotator(coord=['G','C'])

### North galactic pole

In [13]:
theta_gal, phi_gal = 0., 0.
theta_cel, phi_cel = r(theta_gal, phi_gal)
np.rad2deg((np.pi/2-theta_cel, phi_cel)),theta_cel, phi_cel

(array([  27.12884513, -167.14056927]),
 1.0973086569494477,
 -2.9171532473400954)

In [9]:
nx,ny=3,3
x = np.linspace(1,nx, nx)
y = np.linspace(1,ny, ny)
xx, yy = np.meshgrid(x, y)
r(yy.flatten(),xx.flatten())

array([[ 0.98205587,  0.15923708,  0.74049514,  1.42621127,  0.91354846,
         1.22213644,  1.98189695,  1.90409671,  1.94868434],
       [-1.74468   , -2.03865616,  2.14139433, -0.76743698,  0.05705187,
         1.04231409,  0.08373873,  0.20277531,  0.33920273]])

### South galactic pole

In [18]:
theta_gal, phi_gal = np.pi, 0.
theta_cel, phi_cel = r(theta_gal, phi_gal)
np.rad2deg((np.pi/2-theta_cel, phi_cel))

array([-27.12884513,  12.85943073])

### <h1><center style="font-size: 24px">Using Astropy</center></h1>

In [3]:
from astropy import units as u
from astropy.coordinates import SkyCoord

### North galactic pole

In [9]:
c = SkyCoord(ra=192.85948402*u.degree, dec=27.12829637*u.degree, frame='fk5')
c.galactic

<SkyCoord (Galactic): (l, b) in deg
    (119.76037855, 89.99995474)>

In [12]:
g = SkyCoord(l=00*u.degree, b=90*u.degree, frame='galactic')
g.fk5

<SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg
    (192.85948121, 27.12825118)>

In [34]:
#help(c)

### General transformation healpy versus astropy: self consistency relation

In [12]:
r = hp.rotator.Rotator(coord=['c','g'])
totoa,totob=10.,20.
cc=SkyCoord(ra=totoa*u.degree, dec=totob*u.degree, frame='fk5')
lon1,lat1=cc.galactic.l.degree,cc.galactic.b.degree
facta,factb=np.array([totoa,totob])*np.pi/180.
colat2,lon2=r(np.pi/2.-factb,facta)*180./np.pi
lon1,lat1,lon2,90.-colat2

(119.26935674424578,
 -42.79039390791354,
 119.26960565026057,
 -42.78980404570575)

### Reverse from galactic (colat,lon) to (ra,dec)

In [26]:
rinv = hp.rotator.Rotator(coord=['g','c'])

In [27]:
codecinv,rainv=rinv((colat2)*np.pi/180.,lon2*np.pi/180.)*180./np.pi
rainv,90.-codecinv

(10.000000000000007, 20.000000000000014)